import { settingsControlColorsFor } from '@/theme/settings-control-colors'
import { controlSize, typeScale, useAppColors, type ThemeColors } from '@/theme/tokens'
import { deviceLayout } from '@/utils/device-layout'
import { settingsLayout } from '@/utils/settings-layout'
import { useMemo } from 'react'
import { Platform, StyleSheet } from 'react-native'

export function useSettingsStyles() {
  const colors = useAppColors()
  return useMemo(() => createStyles(colors), [colors])
}

export function createStyles(colors: ThemeColors) {
  const controlColors = settingsControlColorsFor(colors)
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.canvas },
  keyboard: { flex: 1 },
  detailHeader: { minHeight: 56, paddingHorizontal: 12, paddingVertical: 6, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: colors.canvas },
  detailTitle: { flex: 1, minWidth: 0, color: colors.text, fontSize: typeScale.heading, fontWeight: '900', textAlign: 'center' },
  backButton: { width: settingsLayout.minimumTouchTarget, height: settingsLayout.minimumTouchTarget, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  headerSpacer: { width: settingsLayout.minimumTouchTarget, height: settingsLayout.minimumTouchTarget },
  detailContent: { width: '100%', maxWidth: deviceLayout.readableContentMaximumWidth, alignSelf: 'center', paddingHorizontal: settingsLayout.detailHorizontalPadding, paddingTop: 18, paddingBottom: 24, gap: 14 },
  detailIntroduction: { minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 2, paddingVertical: 2 },
  detailIntroductionIcon: { width: 36, height: 36, flexShrink: 0, borderRadius: 11, backgroundColor: colors.accentDeep, alignItems: 'center', justifyContent: 'center' },
  detailIntroductionText: { flex: 1, minWidth: 0, color: colors.muted, fontSize: typeScale.label, lineHeight: 18 },
  settingsGroup: { overflow: 'hidden', borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.panel },
  settingsDivider: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  modelCard: { borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.panel, padding: settingsLayout.cardPadding, gap: 10 },
  detailCard: { borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.panel, padding: settingsLayout.cardPadding },
  detailCardBody: { gap: 10 },
  aboutContent: { gap: 16 },
  aboutHero: { alignItems: 'center', paddingTop: 24, paddingBottom: 20, gap: 10 },
  aboutIconFrame: { padding: 5, borderRadius: 28, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border, shadowColor: colors.accent, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.10, shadowRadius: 20, elevation: 3, marginBottom: 8 },
  aboutIcon: { width: 92, height: 92, borderRadius: 23 },
  aboutName: { color: colors.text, fontSize: 28, lineHeight: 34, fontWeight: '900', letterSpacing: -0.7 },
  aboutTagline: { color: colors.muted, fontSize: typeScale.body, textAlign: 'center' },
  aboutVersionCard: { paddingHorizontal: 18, paddingVertical: 4, borderRadius: 20, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border },
  sourceLink: { height: 'auto', minHeight: 84, width: '100%', alignItems: 'center', flexDirection: 'row', justifyContent: 'flex-start', gap: 12, padding: 16, borderRadius: 20, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.panel },
  sourceIcon: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.raised },
  sourceCopy: { flex: 1, minWidth: 0, gap: 5 },
  sourceTitle: { color: colors.text, fontSize: typeScale.body, fontWeight: '700' },
  sourceUrl: { color: colors.muted, fontSize: typeScale.caption, lineHeight: 16, flexShrink: 1 },
  cardLabel: { color: colors.text, fontSize: typeScale.label, fontWeight: '800', marginTop: 2 },
  providerGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: settingsLayout.optionGap },
  providerButton: { height: 'auto', flexGrow: 1, flexBasis: settingsLayout.providerButtonMinimumWidth, minHeight: settingsLayout.minimumTouchTarget, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: controlColors.choiceBackground, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 9, paddingVertical: 8 },
  providerButtonSingleColumn: { flexBasis: '100%' },
  providerButtonActive: { borderColor: controlColors.primaryBackground, backgroundColor: controlColors.primaryBackground },
  providerText: { flexShrink: 1, color: controlColors.choiceForeground, fontSize: typeScale.caption, fontWeight: '800' },
  providerTextActive: { color: controlColors.primaryForeground },
  selector: { height: 'auto', minHeight: controlSize.regular, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.canvas, paddingHorizontal: 12, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 8 },
  selectorText: { flex: 1, minWidth: 0, color: colors.text, fontSize: typeScale.body },
  modelSettingsTitleGroup: { flex: 1, minWidth: 0, gap: 3 },
  modelSettingsDescription: { color: colors.muted, fontSize: typeScale.caption, lineHeight: 18 },
  customSettingsDisclosure: { height: 'auto', minHeight: settingsLayout.minimumTouchTarget, marginTop: 2, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border, borderRadius: 0, paddingHorizontal: 0, paddingTop: 12, paddingBottom: 2, alignItems: 'stretch', justifyContent: 'center' },
  customSettingsDisclosureContent: { width: '100%', flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  customSettingsDisclosureLabel: { color: colors.text, fontSize: typeScale.label, fontWeight: '800', textAlign: 'left' },
  customSettingsChevron: { width: 18, minHeight: 20, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-90deg' }] },
  customSettingsChevronOpen: { transform: [{ rotate: '0deg' }] },
  customSettingsBody: { gap: 10, paddingTop: 2 },
  customSettingsToolbar: { minHeight: 36, alignItems: 'flex-end', justifyContent: 'center' },
  fieldLabel: { color: colors.text, fontSize: typeScale.caption, fontWeight: '800' },
  compactButton: { height: 'auto', minHeight: 36, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 6 },
  compactButtonText: { color: colors.accent, fontSize: typeScale.caption, fontWeight: '800' },
  modelCatalogHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  modelCount: { color: colors.muted, fontSize: typeScale.caption, fontWeight: '700' },
  modelEditorList: { gap: 9 },
  modelEditorRow: { gap: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.raised, padding: 10 },
  modelEditorHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  modelEditorTitle: { flex: 1, minWidth: 0, color: colors.text, fontSize: typeScale.label, fontWeight: '800' },
  modelCapacityRow: { flexDirection: 'row', gap: 8 },
  modelCapacityInput: { flex: 1, minWidth: 0 },
  addModelButton: { alignSelf: 'flex-start', height: 'auto', minHeight: settingsLayout.minimumTouchTarget, borderRadius: settingsLayout.minimumTouchTarget / 2, borderWidth: 1, borderColor: colors.border, backgroundColor: 'transparent', paddingHorizontal: 14, paddingVertical: 8, alignItems: 'center', justifyContent: 'center' },
  addModelButtonContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  addModelButtonText: { color: colors.text, fontSize: typeScale.caption, fontWeight: '800' },
  modelOptionList: { gap: 8 },
  modelOption: { height: 'auto', minHeight: settingsLayout.minimumTouchTarget, borderWidth: 1, borderColor: colors.border, borderRadius: 9, backgroundColor: colors.panel, paddingHorizontal: 0 },
  modelOptionSelected: { borderColor: controlColors.primaryBackground, backgroundColor: controlColors.primaryBackground },
  modelOptionContent: { width: '100%', minHeight: settingsLayout.minimumTouchTarget, justifyContent: 'center', paddingHorizontal: 12, paddingVertical: 8 },
  modelOptionLabel: { width: '100%', color: colors.text, fontSize: typeScale.label, fontWeight: '800', textAlign: 'left' },
  modelOptionLabelSelected: { color: controlColors.primaryForeground },
  textInput: { minHeight: Platform.OS === 'ios' ? settingsLayout.minimumTouchTarget + 2 : settingsLayout.minimumTouchTarget, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.canvas, paddingHorizontal: 12, color: colors.text, fontSize: typeScale.body },
  savedRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  savedText: { color: controlColors.successForeground, fontSize: typeScale.caption, fontWeight: '700' },
  loadingRow: { minHeight: settingsLayout.minimumTouchTarget, flexDirection: 'row', alignItems: 'center', gap: 9 },
  loadingText: { color: colors.muted, fontSize: typeScale.caption },
  pendingActionContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  feedbackAlert: { width: '100%', borderRadius: 10, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.raised, padding: 10 },
  feedbackTitle: { color: colors.text, fontSize: typeScale.label, fontWeight: '900' },
  feedbackText: { color: colors.text, fontSize: typeScale.label, lineHeight: 18 },
  secondaryButton: { height: 'auto', minHeight: settingsLayout.minimumTouchTarget, borderRadius: 10, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.raised, paddingVertical: 8 },
  secondaryButtonText: { color: colors.text, fontSize: typeScale.button, fontWeight: '800' },
  credentialRetryButton: { minHeight: settingsLayout.minimumTouchTarget, alignItems: 'center', justifyContent: 'center' },
  runtimeRetryButton: { minHeight: settingsLayout.minimumTouchTarget, alignItems: 'center', justifyContent: 'center' },
  unconfiguredText: { color: colors.muted, fontSize: typeScale.caption },
  primaryButton: { height: 'auto', minHeight: settingsLayout.minimumTouchTarget, borderRadius: 13, backgroundColor: controlColors.primaryBackground, paddingVertical: 8, alignItems: 'center', justifyContent: 'center' },
  primaryButtonDisabled: { opacity: 0.45 },
  primaryButtonText: { color: controlColors.primaryForeground, fontSize: typeScale.button, fontWeight: '900' },
  dangerButton: { height: 'auto', minHeight: settingsLayout.minimumTouchTarget, borderRadius: 13, borderWidth: 1, borderColor: controlColors.dangerSoftForeground, backgroundColor: controlColors.dangerSoftBackground, paddingVertical: 8, alignItems: 'center', justifyContent: 'center' },
  dangerButtonText: { color: controlColors.dangerSoftForeground, fontSize: typeScale.button, fontWeight: '800' },
  choiceRow: { minHeight: 72, paddingHorizontal: 13, paddingVertical: 11, gap: 9 },
  choiceLabel: { color: colors.text, fontSize: typeScale.label, fontWeight: '800' },
  choiceOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: settingsLayout.optionGap },
  choiceButton: { height: 'auto', minHeight: settingsLayout.minimumTouchTarget, borderRadius: 10, borderWidth: 1, borderColor: colors.border, backgroundColor: controlColors.choiceBackground, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12, paddingVertical: 8 },
  choiceButtonActive: { borderColor: controlColors.choiceSelectedForeground, backgroundColor: controlColors.choiceSelectedBackground },
  choiceText: { color: controlColors.choiceForeground, fontSize: typeScale.caption, fontWeight: '700' },
  choiceTextActive: { color: controlColors.choiceSelectedForeground, fontWeight: '900' },
  choiceDescription: { minWidth: 0, color: colors.muted, fontSize: typeScale.caption, lineHeight: 18 },
  row: { minHeight: settingsLayout.minimumTouchTarget, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14, paddingVertical: 10 },
  rowStacked: { flexDirection: 'column', alignItems: 'stretch', justifyContent: 'flex-start', gap: 4 },
  rowLabel: { minWidth: 0, color: colors.muted, flex: 1, fontSize: typeScale.label },
  rowLabelStacked: { width: '100%', flex: 0 },
  rowValue: { minWidth: 0, color: colors.text, fontSize: typeScale.label, fontWeight: '700', flex: 1.5, textAlign: 'right' },
  rowValueStacked: { width: '100%', flex: 0, textAlign: 'left' },
  sshField: { gap: 4 },
  sshFingerprint: { color: colors.blue, fontFamily: 'monospace', fontSize: typeScale.caption, fontWeight: '800', lineHeight: 18 },
  sshPublicKey: { color: colors.text, fontFamily: 'monospace', fontSize: typeScale.micro, lineHeight: 16, borderRadius: 8, backgroundColor: colors.raised, padding: 10 },
  sshActions: { flexDirection: 'row', flexWrap: 'wrap', gap: settingsLayout.optionGap },
  sshActionButton: { height: 'auto', flexGrow: 1, flexBasis: settingsLayout.providerButtonMinimumWidth, minHeight: settingsLayout.minimumTouchTarget, borderRadius: 13, paddingVertical: 8, alignItems: 'center', justifyContent: 'center' },
  sshPrimaryActionButton: { borderWidth: 1, borderColor: controlColors.primaryBackground },
  sshActionLabel: { flex: 1, minWidth: 0, fontSize: typeScale.button, fontWeight: '800', lineHeight: 20, textAlign: 'center' },
  sshRetryButton: { minHeight: settingsLayout.minimumTouchTarget, alignItems: 'center', justifyContent: 'center' },
  infoCard: { borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.panel, padding: 16, gap: 7 },
  infoTitle: { color: colors.text, fontSize: typeScale.heading, fontWeight: '800' },
  infoBody: { color: colors.muted, fontSize: typeScale.label, lineHeight: 18 },
  })
}
